顧客検索にカナ検索追加
egg-system/olive-back pull request #227
Opened 2021-01-19 11:43 UTC by natsume0718

# 概要

顧客画面でカタカナ検索をできるようにする

# 変更点

 - カナ氏名欄の追加
 - 顧客の表示テーブルにカナ氏名欄追加
 - 顧客の表示テーブルの文字の折返しをなくし、横スクロールできるように

2021-01-19 11:45 UTC, natsume0718 commented
# 確認したい点

 - 予約画面の検索にはカタカナ検索不要でしょうか？

 - 顧客の表示テーブルの文字の折返しをなくし、横スクロールできるようにしましたがだめな場合は教えて下さい

2021-01-20 01:21 UTC, nuno929 commented
@natsume0718 
顧客と調整しましたので、下記の点をご対応よろしくお願いいたします。
- 照合順序を指定して、カタカナとひらがなの両方が検索結果に表示されるようにする
- 横スクロールは使い勝手が悪いので、戻す
- 予約管理画面にもかな検索を実装する

2021-01-22 05:01 UTC, natsume0718 commented
@nuno929 

> 照合順序を指定して、カタカナとひらがなの両方が検索結果に表示されるようにする
対応しました

> 横スクロールは使い勝手が悪いので、戻す
revertしました

> 予約管理画面にもかな検索を実装する
追加しました
テーブルにもカナ欄追加しました
テーブルに欄多い場合はルビを振るのもありかなと思いました。

お手すきの際に再度ご確認よろしくお願いします

2021-01-22 05:19 UTC, natsume0718 commented
複雑度チェックに引っかかった模様です
後日対応します

app/controllers/concerns/reservation_searchable.rb:4:3: C: Metrics/CyclomaticComplexity: Cyclomatic complexity for search_reservations is too high. [13/12]
  def search_reservations ...
  ^^^^^^^^^^^^^^^^^^^^^^^
app/controllers/concerns/reservation_searchable.rb:4:3: C: Metrics/PerceivedComplexity: Perceived complexity for search_reservations is too high. [14/13]
  def search_reservations ...
  ^^^^^^^^^^^^^^^^^^^^^^^

2021-01-24 06:45 UTC, nuno929 requested changes

2021-01-24 06:45 UTC, nuno929 commented on src/app/views/customers/index.html.erb
> +            <th>カナ氏名</th>
ラベルはカナでよろしくお願いいたします。

2021-01-24 06:45 UTC, nuno929 commented on src/app/views/reservations/_list.html.erb
> +            <th scope="col">顧客カナ名</th>
列が増えると見づらいですね...
顧客列にして、下記のような三段にしていただければと思います。
- 氏名：テスト太郎
- カナ：テストタロウ
- 電話番号：09099999999

2021-01-24 06:45 UTC, nuno929 commented on src/app/views/reservations/_search.html.erb
> +          <th>顧客カナ名</th>
顧客カナにしていいただければと思います。

2021-01-24 06:45 UTC, nuno929 commented on src/app/views/customers/_table.html.erb
> +      <th scope="col">カナ氏名</th>
カナにしていただければと思います。

2021-02-02 07:51 UTC, nuno929 commented on src/app/views/reservations/_list.html.erb
> +            <th scope="col">顧客</th>
列名を顧客情報に変更していただければと思います。
クライアントFB次第では、変更あるかもしれないですが、一旦は大丈夫です！

2021-02-05 01:59 UTC, natsume0718 commented on src/app/views/reservations/_list.html.erb
> +            <th scope="col">顧客</th>
修正しました

2021-02-16 18:36 UTC, merged