非表示フラグの追加
egg-system/olive-back pull request #237
Opened 2021-03-27 17:56 UTC by natsume0718

# 概要
妊娠や出産で一時的に離職するスタッフがいる。（出産後に復帰予定）  
管理画面から予約登録する時、一時的に離職しているスタッフも選択肢に入ってしまうと間違えてしまうので、離職中のスタッフは予約登録時に選択できないようにしたい。

# 仕様
## スタッフマスタ
・「非表示フラグ」（チェックボックス）を新設  
・デフォルトは「OFF」

## 予約登録
【フロントからお客様が予約したとき】  
・対応不要  
→シフトが登録されていないハズなので。  

【管理画面からスタッフが予約したとき】  
- 予約登録時「非表示フラグ」でも選択する(仕様変更)
- 予約情報を更新する際も、「非表示フラグ」がONのスタッフはプルダウンの選択リストに表示させない

【非表示フラグがONのスタッフは以下のプルダウンに表示させないようにする】
- 管理画面トップの予約カレンダーにおけるスタッフ選択プルダウン
- 予約管理画面の検索項目の担当者選択プルダウン
- シフト管理画面のスタッフ選択プルダウン
- 経過記録新規登録画面の担当者選択プルダウン

## 注意事項

・既に登録されている予約データには影響を及ぼさないこと  
→スタッフAに対して非表示ONを設定しても、過去の予約データを開けば「担当スタッフA」と表示されること"

2021-03-28 22:06 UTC, eggsystem commented
@natsume0718 @kanahebi 
一応こちらでもコメントを！

>予約情報を登録する際は、「非表示フラグ」がONでも選択対象にする
これはOK。

>予約情報を更新する際は、「非表示フラグ」がONのスタッフはプルダウンの選択リストに表示させない
これが違う。
プルダウンの選択リストに表示させないのは、改めて指定した下記の4箇所のみ。
　　→　管理画面トップの予約カレンダーにおけるスタッフ選択プルダウン
　　→　予約管理画面の検索項目の担当者選択プルダウン
　　→　シフト管理画面のスタッフ選択プルダウン
　　→　経過記録新規登録画面の担当者選択プルダウン

2021-03-29 02:31 UTC, kanahebi requested changes
いくつかコメントしました！

2021-03-29 02:31 UTC, kanahebi commented on src/app/controllers/observations_controller.rb
> +    @staffs_exclude_hidden = Staff.exclude_hidden.all
ここ、`all` 不要だと思われます！

2021-03-29 02:31 UTC, kanahebi commented on src/db/migrate/20210326064355_add_hidden_to_staffs.rb
> +class AddHiddenToStaffs < ActiveRecord::Migration[5.2]
同じ内容のマイグレーションファイルが2つ・・・？
見間違いかもですが・・・

2021-03-29 02:31 UTC, kanahebi commented on src/db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_03_26_064355) do
マイグレートした後のこのファイルの差分もコミットした方が良さそうです！

2021-03-29 12:49 UTC, natsume0718 commented on src/db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_03_26_064355) do
マイグレートした後の差分だと思います！

2021-03-29 12:49 UTC, natsume0718 commented on src/db/migrate/20210326064355_add_hidden_to_staffs.rb
> +class AddHiddenToStaffs < ActiveRecord::Migration[5.2]
削除しました

2021-04-01 06:15 UTC, kanahebi requested changes
すみません！一点だけ修正お願いします！！

2021-04-01 06:15 UTC, kanahebi commented on src/db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_03_26_064355) do
マイグレートした後の差分が足りないと思います！！

2021-04-01 06:34 UTC, moto-taka commented on src/db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_03_26_064355) do
内容が理解できないです
どのような差分が出ますか

2021-04-01 07:03 UTC, kanahebi approved these changes

2021-04-01 08:35 UTC, merged