CSVのエクスポート機能
egg-system/olive-back pull request #260
Opened 2021-05-30 13:42 UTC by natsume0718

# 概要
CSVのエクスポート機能の作成

管理者権限のみダウンロード可能。

# 技術的変更
 - downloadをjsで処理するようにコンポーネント作成
 - CSV生成処理追加

2021-05-31 03:01 UTC, kanahebi requested changes
いくつかコメントしました！

2021-06-01 15:42 UTC, natsume0718 commented on src/app/controllers/customers/csv_controller.rb
> +  def generate_customer_data
ビジネスロジックでないテンプレートみたいなものなのでviewに切り出しました！

2021-06-01 15:42 UTC, natsume0718 commented on src/app/controllers/customers/csv_controller.rb
> +  require 'csv'
他のクラスと統一してます！

2021-06-04 07:52 UTC, kanahebi requested changes

2021-06-04 07:52 UTC, kanahebi commented on src/app/views/customers/csv/index.csv.erb
> +<%=
viewsにした理由はなんでしょうか？

2021-06-04 07:56 UTC, kanahebi approved these changes

2021-08-03 05:48 UTC, merged